/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otc;

import Pacote_Principal.LoginBanco;
import QueryS.GerarOtc;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author henrique.rodrigues
 */


public class Otc extends javax.swing.JFrame {

    
     public static ArrayList<String> ListaOtc = new ArrayList<String> ();
     
    public static int somaOtc=0; 
    /**
     * Creates new form Otc
     */
    public Otc() {
        initComponents();
        
        //inserindo imagem no fundo 
        TelaOtc.setImagem(new File("C:\\Automacao_Mobile\\Imagem\\Tela_Principal2.jpg"));
        //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());
    
        //---------Alterando o OptionPane            
     UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Segoe UI Semibold",Font.PLAIN,15)));
        
        
        
        //Pegando o nome do Banco
        NomeBanco.setText(LoginBanco.nomeBancoConectado);
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaOtc = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        scrollCpf = new javax.swing.JScrollPane();
        areaText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        NomeBanco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valorOtc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter aux= new javax.swing.text.MaskFormatter("##/##/####");
            data = new javax.swing.JFormattedTextField(aux);
        }
        catch (Exception e){
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerar OTC");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GERAR OTC");

        scrollCpf.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        areaText.setColumns(9);
        areaText.setRows(5);
        areaText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de msisdn´s", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 11))); // NOI18N
        scrollCpf.setViewportView(areaText);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NomeBanco.setBackground(new java.awt.Color(204, 204, 204));
        NomeBanco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NomeBanco.setForeground(new java.awt.Color(255, 0, 0));
        NomeBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeBanco.setText("Conectado: MOBILE 12");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de Ativação");

        valorOtc.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        valorOtc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorOtc.setText("89,99");
        valorOtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorOtcActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor da oferta:");

        data.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        data.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout TelaOtcLayout = new javax.swing.GroupLayout(TelaOtc);
        TelaOtc.setLayout(TelaOtcLayout);
        TelaOtcLayout.setHorizontalGroup(
            TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaOtcLayout.createSequentialGroup()
                .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaOtcLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(NomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TelaOtcLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(TelaOtcLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorOtc))
                                    .addGroup(TelaOtcLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scrollCpf, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        TelaOtcLayout.setVerticalGroup(
            TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaOtcLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorOtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(TelaOtcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(NomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaOtc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TelaOtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void valorOtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorOtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorOtcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



// pegando varios lista de CPF criando o parametro para oferta
String texto2 = areaText.getText() ;
StringTokenizer st2 = new StringTokenizer(texto2,"\n") ;
while (st2.hasMoreTokens()){
 
 
    String line2 = st2.nextToken();
    ListaOtc.add(line2);
    somaOtc ++;
    System.out.println("Quantidade de Otc a ser Gerado: "+ somaOtc );
    System.out.println("Lista otc : "+ ListaOtc +" data: "+ data.getText() );
   
}

GerarOtc otc = new GerarOtc();

if (otc.GerarOtc(ListaOtc , data.getText(),valorOtc.getText())){
    JOptionPane.showMessageDialog(null, "Otc Gerado com sucesso");
}else{
     JOptionPane.showMessageDialog(null, "Otc Gerado com Falha");
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Otc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NomeBanco;
    private componentes.UJPanelImagem TelaOtc;
    private javax.swing.JTextArea areaText;
    private javax.swing.JTextField data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane scrollCpf;
    private javax.swing.JTextField valorOtc;
    // End of variables declaration//GEN-END:variables
}
