/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MassaWa;

import MassaMobile.*;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author henrique.rodrigues
 */
public class SelecaoOferta extends javax.swing.JFrame {

    
 
	public static String TipoOfertaTexto = "",TipoOfertaSelect="";
	String ativar="",titulo, plano;
    
    
    
    
    /**
     * Creates new form SelecaoOferta2
     */
    public SelecaoOferta() {
        initComponents();
        
        
         //inserindo imagem no fundo 
        TelaOferta.setImagem(new File("C:\\Automacao_Mobile\\Imagem\\Tela_Principal2.jpg"));
        
             //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());
    
        
        //oculto informações adicionais
        text1.setVisible(false);
        text2.setVisible(false);
        text3.setVisible(false);
        text4.setVisible(false);
        text5.setVisible(false);
        text6.setVisible(false);
        text7.setVisible(false);
        text8.setVisible(false);
        text9.setVisible(false);
        text10.setVisible(false);
        text11.setVisible(false);
        text12.setVisible(false);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(false);
        text17.setVisible(false);
        text18.setVisible(false);
        voltar.setVisible(false);
        
 
        
    }
    
    public  boolean Ocultar (){
        
        boolean oculto;
      //oculto informações adicionais
        text1.setVisible(false);
        text2.setVisible(false);
        text3.setVisible(false);
        text4.setVisible(false);
        text5.setVisible(false);
        text6.setVisible(false);
        text7.setVisible(false);
        text8.setVisible(false);
        text9.setVisible(false);
        text10.setVisible(false);
        text11.setVisible(false);
        text12.setVisible(false);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(false);
        text17.setVisible(false);
        text18.setVisible(false);
        voltar.setVisible(false);
        oculto =true;
        return oculto ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaOferta = new componentes.UJPanelImagem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        TClienteNome = new javax.swing.JLabel();
        TClienteNome1 = new javax.swing.JLabel();
        btn2G = new javax.swing.JButton();
        TClienteNome2 = new javax.swing.JLabel();
        TClienteNome3 = new javax.swing.JLabel();
        btn5G = new javax.swing.JButton();
        btn6G = new javax.swing.JButton();
        btn3G = new javax.swing.JButton();
        btn7G = new javax.swing.JButton();
        btn14G = new javax.swing.JButton();
        btn9G = new javax.swing.JButton();
        btn25G = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnloT = new javax.swing.JButton();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JButton();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        text7 = new javax.swing.JButton();
        text8 = new javax.swing.JLabel();
        text9 = new javax.swing.JLabel();
        text10 = new javax.swing.JLabel();
        text11 = new javax.swing.JButton();
        text12 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        text13 = new javax.swing.JLabel();
        text14 = new javax.swing.JLabel();
        text15 = new javax.swing.JButton();
        text17 = new javax.swing.JLabel();
        text18 = new javax.swing.JLabel();
        text16 = new javax.swing.JSeparator();
        btn30GB = new javax.swing.JButton();
        btn50GB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oferta Nivel Contrato");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TClienteNome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        TClienteNome.setForeground(new java.awt.Color(204, 0, 0));
        TClienteNome.setText("INTERNET");

        TClienteNome1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome1.setText("Escolha o Pacote de Internet que mais se adéqua ao perfil do seu cliente");

        btn2G.setBackground(new java.awt.Color(255, 255, 255));
        btn2G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn2G.setText("2GB");
        btn2G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2GActionPerformed(evt);
            }
        });

        TClienteNome2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome2.setText("* Após o consumo da franquia a navegação será bloqueada com opção de compra de pacote adicional. ");

        TClienteNome3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome3.setText("* Para o plano Claro Light após o consumo do bônus de 100MB a navegação será bloqueada.");

        btn5G.setBackground(new java.awt.Color(255, 255, 255));
        btn5G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn5G.setText("5GB");
        btn5G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5GActionPerformed(evt);
            }
        });

        btn6G.setBackground(new java.awt.Color(255, 255, 255));
        btn6G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn6G.setText("6GB");
        btn6G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6GActionPerformed(evt);
            }
        });

        btn3G.setBackground(new java.awt.Color(255, 255, 255));
        btn3G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn3G.setText("3GB");
        btn3G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3GActionPerformed(evt);
            }
        });

        btn7G.setBackground(new java.awt.Color(255, 255, 255));
        btn7G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn7G.setText("7GB");
        btn7G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7GActionPerformed(evt);
            }
        });

        btn14G.setBackground(new java.awt.Color(255, 255, 255));
        btn14G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn14G.setText("14GB");
        btn14G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14GActionPerformed(evt);
            }
        });

        btn9G.setBackground(new java.awt.Color(255, 255, 255));
        btn9G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn9G.setText("9GB");
        btn9G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9GActionPerformed(evt);
            }
        });

        btn25G.setBackground(new java.awt.Color(255, 255, 255));
        btn25G.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn25G.setText("25GB");
        btn25G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn25GActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton9.setText("100GB");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnloT.setBackground(new java.awt.Color(255, 255, 255));
        btnloT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnloT.setText("loT");
        btnloT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloTActionPerformed(evt);
            }
        });

        text1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        text1.setForeground(new java.awt.Color(204, 0, 0));
        text1.setText("LIGAÇÕES LOCAIS");

        text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text2.setText("Escolha a quantidade de minutos locais que seu cliente deseja para falar com outros celulares e telefones fixos:");

        text3.setBackground(new java.awt.Color(153, 0, 0));
        text3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        text3.setText("9GB");

        text4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        text4.setText("* Ligações ilimitadas para Claro, Claro Fixo e Net Fone inclusas no plano.");

        text5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        text5.setForeground(new java.awt.Color(204, 0, 0));
        text5.setText("LIGAÇÕES LONGA DISTÂNCIA");

        text6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text6.setText("Ligações ilimitadas de longa distância nacional para Claro, Claro Fixo e Net fone, e roaming nacional grátis.");

        text7.setBackground(new java.awt.Color(153, 0, 0));
        text7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        text7.setForeground(new java.awt.Color(255, 255, 255));
        text7.setText("SIM");

        text8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        text8.setText("* Válido para ligações com o 21.");

        text9.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        text9.setForeground(new java.awt.Color(204, 0, 0));
        text9.setText("TORPEDOS");

        text10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text10.setText("Torpedos ilimitados para qualquer operadora nacional.");

        text11.setBackground(new java.awt.Color(153, 0, 0));
        text11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        text11.setForeground(new java.awt.Color(255, 255, 255));
        text11.setText("SIM");

        text12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        text12.setText("* O plano Claro Light possui torpedos ilimitados apenas de Claro para Claro.");

        voltar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        text13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        text13.setForeground(new java.awt.Color(204, 0, 0));
        text13.setText("AGRUPADOR SVA");

        text14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text14.setText("Selecione o agrupador SVA");

        text15.setBackground(new java.awt.Color(153, 0, 0));
        text15.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        text15.setForeground(new java.awt.Color(255, 255, 255));
        text15.setText("Combo SVA 1");
        text15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text15ActionPerformed(evt);
            }
        });

        text17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        text17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text17.setText("Claro Pos Giga 5GB + 200 minutos ");

        text18.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        text18.setForeground(new java.awt.Color(204, 0, 0));
        text18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text18.setText("R$ 178,48 ");

        btn30GB.setBackground(new java.awt.Color(255, 255, 255));
        btn30GB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn30GB.setText("30GB");
        btn30GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30GBActionPerformed(evt);
            }
        });

        btn50GB.setBackground(new java.awt.Color(255, 255, 255));
        btn50GB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn50GB.setText("50GB");
        btn50GB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn50GBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(text18, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text13, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text12, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(text17, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(text11)
                                        .addComponent(text15)
                                        .addComponent(text16, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TClienteNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btn30GB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn50GB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnloT))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn2G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn3G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn5G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn6G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn7G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn9G)
                                        .addGap(15, 15, 15)
                                        .addComponent(btn14G)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn25G))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TClienteNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TClienteNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(text7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(text3))
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TClienteNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn25G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn30GB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn50GB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TClienteNome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TClienteNome3)
                .addGap(30, 30, 30)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(text4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text12)
                .addGap(18, 18, 18)
                .addComponent(text13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text17)
                .addGap(11, 11, 11)
                .addComponent(text18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OFERTA CLARO MAX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout TelaOfertaLayout = new javax.swing.GroupLayout(TelaOferta);
        TelaOferta.setLayout(TelaOfertaLayout);
        TelaOfertaLayout.setHorizontalGroup(
            TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaOfertaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        TelaOfertaLayout.setVerticalGroup(
            TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TelaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TelaOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

      System.out.println("Tipo de Oferta Selecionada na Claro Conta: "+TipoOfertaSelect);
    dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_voltarActionPerformed

    private void btn3GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3GActionPerformed
                    
        Ocultar();
              
      if (btn3G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("175");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 3GB + 175 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 136,48"); 
        voltar.setVisible(true);
         TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[2]/span";
      }else{
           Ocultar();   
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3GActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        TipoOfertaSelect= "";
   Ocultar();
    text5.setVisible(true);
        text5.setText("O plano 14918 não foi encontrado");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void text15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text15ActionPerformed

    private void btn2GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2GActionPerformed

           Ocultar();
              
      if (btn2G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("150");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);       
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 2GB + 150 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 115,48"); 
        voltar.setVisible(true);
         TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[1]/span";
      }else{
           Ocultar();   
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2GActionPerformed

    private void btn5GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5GActionPerformed

                           Ocultar();
              
      if (btn5G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("200");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(true);
        text14.setVisible(true);
        text15.setVisible(true);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 5GB + 200 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 178,48"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[3]/span";
      }else{
           Ocultar();   
      }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn5GActionPerformed

    private void btn6GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6GActionPerformed

     Ocultar();
              
      if (btn6G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("300");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 6GB + 300 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 209,98"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[4]/span";
      }else{
           Ocultar();   
      }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn6GActionPerformed

    private void btn7GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7GActionPerformed

     Ocultar();
              
      if (btn7G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("500");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 7GB + 500 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 241,48"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[5]/span";
      }else{
           Ocultar();   
      }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn7GActionPerformed

    private void btn9GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9GActionPerformed


     Ocultar();
              
      if (btn9G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("900");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 9GB + 900 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 314,98"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[6]/span";
      }else{
           Ocultar();   
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn9GActionPerformed

    private void btn14GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14GActionPerformed

     Ocultar();
              
      if (btn14G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("3000");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 14GB + 3000 minutos"); 
        text18.setVisible(true);
        text18.setText("R$ 404,23"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[7]/span";
      }else{
           Ocultar();   
      }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn14GActionPerformed

    private void btn25GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn25GActionPerformed

         Ocultar();
              
      if (btn25G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("Ilimitados");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(true);
        text14.setVisible(true);
        text15.setVisible(true);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pos Giga 25GB + minutos ilimitados"); 
        text18.setVisible(true);
        text18.setText("R$ 524,98"); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[8]/span";
      }else{
           Ocultar();   
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn25GActionPerformed

    private void btnloTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloTActionPerformed

                    
        Ocultar();
              
      if (btn3G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("IR");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text7.setText("NAO");
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Internet das Coisas"); 
        text18.setVisible(true);
        text18.setText("R$ 40,00"); 
        voltar.setVisible(true);
         TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[10]/span";
      }else{
           Ocultar();   
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnloTActionPerformed

    private void btn30GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30GBActionPerformed


         Ocultar();
              
      if (btn25G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("Ilimitados");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(true);
        text14.setVisible(true);
        text15.setVisible(true);
        text15.setText("Novo Plano Pós");
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText(""); 
        text18.setVisible(true);
        text18.setText(""); 
        voltar.setVisible(true);
        TipoOfertaSelect= "//*[@id=\"resposta_1\"]/label[5]/span";
      }else{
           Ocultar();   
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn30GBActionPerformed

    private void btn50GBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn50GBActionPerformed

         Ocultar();
              
      if (btn25G.isFocusable() == true){
        text1.setVisible(true);
        text2.setVisible(true);
        text3.setVisible(true);
        text3.setText("Ilimitados");
        text4.setVisible(true);
        text5.setVisible(true);
        text6.setVisible(true);
        text7.setVisible(true);
        text8.setVisible(true);
        text9.setVisible(true);
        text10.setVisible(true);
        text11.setVisible(true);
        text12.setVisible(true);
        text13.setVisible(false);
        text14.setVisible(false);
        text15.setVisible(false);       
        text16.setVisible(true);
        text17.setVisible(true);
        text17.setText("Claro Pós Mais 50GB"); 
        text18.setVisible(true);
        text18.setText("R$ 459,99"); 
        voltar.setVisible(true);
        TipoOfertaSelect=  "//*[@id=\"resposta_1\"]/label[6]/span";
                                
      }else{
           Ocultar();   
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn50GBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TClienteNome;
    private javax.swing.JLabel TClienteNome1;
    private javax.swing.JLabel TClienteNome2;
    private javax.swing.JLabel TClienteNome3;
    private componentes.UJPanelImagem TelaOferta;
    private javax.swing.JButton btn14G;
    private javax.swing.JButton btn25G;
    private javax.swing.JButton btn2G;
    private javax.swing.JButton btn30GB;
    private javax.swing.JButton btn3G;
    private javax.swing.JButton btn50GB;
    private javax.swing.JButton btn5G;
    private javax.swing.JButton btn6G;
    private javax.swing.JButton btn7G;
    private javax.swing.JButton btn9G;
    private javax.swing.JButton btnloT;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text10;
    private javax.swing.JButton text11;
    private javax.swing.JLabel text12;
    private javax.swing.JLabel text13;
    private javax.swing.JLabel text14;
    private javax.swing.JButton text15;
    private javax.swing.JSeparator text16;
    private javax.swing.JLabel text17;
    private javax.swing.JLabel text18;
    private javax.swing.JLabel text2;
    private javax.swing.JButton text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JButton text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel text9;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
