/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MassaWa;

import MassaMobile.*;
import Pacote_Principal.LoginBanco;
import Pacote_Principal.SystemOut;
import Pacote_Principal.Transfers;
import QueryS.GerarIccd;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author henrique.rodrigues
 */
public class Tela_WA extends javax.swing.JFrame {

    public static int TplanoN = 0, r_completo = 0, somaContrato = 0, somaCPF = 0, somaCustomer = 0, r_cliente = 0, r_conta = 0, r_oferta = 0, r_assinante = 0, TnumeroEmpresa, ofertaAtiva = 0;
    public static String tipoNavegador = "", numeroEmpresa = "", TVencimento = "", getCliente = "", auxCliente = "", getSubTipo = "", habilitadoNavegador = "", TQuantidadeMassa, T_Cliente, TipoNomeSubTipo, Tcyclo, Tlink, TnumeroCyclo, TCustomerNumero, Tcontrato;
    public static Boolean liberarAutomacao = false, auxCiclo = false, auxOferta = false;
    private Color oldColor = null;
    public static ArrayList<String> iccd100 = new ArrayList<String>();
    public static ArrayList<String> ListaCustomer = new ArrayList<String>();
    public static ArrayList<String> ListaCPF = new ArrayList<String>();
    public static ArrayList<String> ListaContrato = new ArrayList<String>();

    /**
     * Creates new form Tela_Mobile
     */
    public Tela_WA() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
        
         
        //Pegando o nome do Banco
        NomeBanco.setText(LoginBanco.nomeBancoConectado);
        
        //Pegando o nome do usuario
        String NomeUsuario = System.getProperty("user.name");
        //NomeUsuario = NomeUsuario.replaceAll(".", " ");
        usuarioNome.setText("Bem vindo: "+NomeUsuario);
        
        
        //inserindo imagem no fundo 
        TelaPrincipal.setImagem(new File(LoginBanco.caminhoRedeLogin+"\\Imagem\\Tela_Principal2.jpg"));
        //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());

        //---------Alterando o OptionPane            
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Segoe UI Semibold", Font.PLAIN, 15)));

        //Pegando o nome do Banco
        
        NomeBanco.setText(LoginBanco.nomeBancoConectado);

        //Deixando Todos campo inviseveis
        //Area do tipo de cliente
        //   TClienteNome.setVisible(false);
        // boxCliente.setVisible(false);
       // TChrome.setVisible(false);
        Firefox.setVisible(false);
        boxClienteS.setVisible(false);
        TClientenomeSubTipo.setVisible(false);
        gerarCpfAutomatico.setVisible(false);
        painelCpf.setVisible(false);
        TClientenomeVencimento.setVisible(false);
        TVencimentoFatura.setVisible(false);
         planoPreco.setVisible(false);
        // Area tipo Oferta
        addOferta.setVisible(false);
        addDenpendente.setVisible(false);
        iniciar.setVisible(false);
        TPlanoPreco.setVisible(false);
   
        //Estabelecendo parametros
        areaTextCpf.setDocument(new Numeric(1000));
        TVencimentoFatura.setDocument(new Numeric(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipal = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        boxCliente = new javax.swing.JComboBox<>();
        TClienteNome = new javax.swing.JLabel();
        TClientenomeSubTipo = new javax.swing.JLabel();
        boxClienteS = new javax.swing.JComboBox<>();
        gerarCpfAutomatico = new javax.swing.JRadioButton();
        addOferta = new javax.swing.JButton();
        painelCpf = new javax.swing.JPanel();
        scrollCpf = new javax.swing.JScrollPane();
        areaTextCpf = new javax.swing.JTextArea();
        TClientenomeVencimento = new javax.swing.JLabel();
        TVencimentoFatura = new javax.swing.JTextField();
        addDenpendente = new javax.swing.JButton();
        planoPreco = new javax.swing.JComboBox<>();
        TPlanoPreco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TQuantidade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TLink = new javax.swing.JTextField();
        iE = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        TChrome = new javax.swing.JRadioButton();
        NomeBanco = new javax.swing.JLabel();
        usuarioNome = new javax.swing.JLabel();
        Firefox = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        scrollNumeroContrato1 = new javax.swing.JScrollPane();
        areaTextNumeroIccd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Massa WA");
        setResizable(false);

        TelaPrincipal.setForeground(new java.awt.Color(0, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASSA WA");

        iniciar.setBackground(new java.awt.Color(255, 153, 0));
        iniciar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        iniciar.setText("INICIAR");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        boxCliente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "CLARO CARTAO", "CLARO CONTROLE", "CLARO CONTA" }));
        boxCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        boxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClienteActionPerformed(evt);
            }
        });

        TClienteNome.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome.setText("Tipo de Plano");

        TClientenomeSubTipo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClientenomeSubTipo.setText("Tipo de Tecnologia");

        boxClienteS.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        boxClienteS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        boxClienteS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClienteSActionPerformed(evt);
            }
        });

        gerarCpfAutomatico.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        gerarCpfAutomatico.setText("Gerar CPF Automatico");
        gerarCpfAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarCpfAutomaticoActionPerformed(evt);
            }
        });

        addOferta.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        addOferta.setText("ADICIONE OFERTA");
        addOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOfertaActionPerformed(evt);
            }
        });

        scrollCpf.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        areaTextCpf.setColumns(9);
        areaTextCpf.setRows(5);
        areaTextCpf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicione CPF", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 11))); // NOI18N
        scrollCpf.setViewportView(areaTextCpf);

        javax.swing.GroupLayout painelCpfLayout = new javax.swing.GroupLayout(painelCpf);
        painelCpf.setLayout(painelCpfLayout);
        painelCpfLayout.setHorizontalGroup(
            painelCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollCpf)
        );
        painelCpfLayout.setVerticalGroup(
            painelCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        TClientenomeVencimento.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClientenomeVencimento.setText("Vencimento Fatura.");

        TVencimentoFatura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TVencimentoFatura.setText("15");

        addDenpendente.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        addDenpendente.setText("ADICIONE DENPENDENTE");
        addDenpendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDenpendenteActionPerformed(evt);
            }
        });

        planoPreco.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        planoPreco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        planoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planoPrecoActionPerformed(evt);
            }
        });

        TPlanoPreco.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TPlanoPreco.setText("Tipo de Plano");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(gerarCpfAutomatico, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(painelCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TClientenomeVencimento)
                                .addGap(84, 84, 84)
                                .addComponent(TVencimentoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addDenpendente, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TClientenomeSubTipo)
                            .addComponent(boxClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TClienteNome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(planoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TPlanoPreco)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TClienteNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TClientenomeSubTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TPlanoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TClientenomeVencimento)
                    .addComponent(TVencimentoFatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addOferta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDenpendente)
                .addGap(23, 23, 23)
                .addComponent(gerarCpfAutomatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUANTIDADE MASSA:");

        TQuantidade.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        TQuantidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        TQuantidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LINK DO WA:");

        TLink.setText("http://trairi:6141/ativacao/login.jsp");
        TLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TLinkActionPerformed(evt);
            }
        });

        iE.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        iE.setForeground(new java.awt.Color(255, 255, 255));
        iE.setText("Internet Explorer");
        iE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iEActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Será Criado uma Pasta na area de trabalho para 'EVIDENCIAS'");

        TChrome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        TChrome.setForeground(new java.awt.Color(255, 255, 255));
        TChrome.setText("CHROME");
        TChrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TChromeActionPerformed(evt);
            }
        });

        NomeBanco.setBackground(new java.awt.Color(204, 204, 204));
        NomeBanco.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        NomeBanco.setForeground(new java.awt.Color(0, 204, 0));
        NomeBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeBanco.setText("Conectado: MOBILE 12");

        usuarioNome.setBackground(new java.awt.Color(204, 204, 204));
        usuarioNome.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        usuarioNome.setForeground(new java.awt.Color(255, 255, 255));
        usuarioNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioNome.setText("Bem vindo!");

        Firefox.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Firefox.setForeground(new java.awt.Color(255, 255, 255));
        Firefox.setText("Firefox");
        Firefox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirefoxActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        scrollNumeroContrato1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        areaTextNumeroIccd.setColumns(9);
        areaTextNumeroIccd.setRows(5);
        areaTextNumeroIccd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicione nº Iccd", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 11))); // NOI18N
        scrollNumeroContrato1.setViewportView(areaTextNumeroIccd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollNumeroContrato1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollNumeroContrato1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TelaPrincipalLayout = new javax.swing.GroupLayout(TelaPrincipal);
        TelaPrincipal.setLayout(TelaPrincipalLayout);
        TelaPrincipalLayout.setHorizontalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TLink, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalLayout.createSequentialGroup()
                                        .addComponent(usuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalLayout.createSequentialGroup()
                                        .addComponent(NomeBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83))))))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Firefox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addGap(284, 284, 284)
                                .addComponent(jLabel2))
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(iE, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(252, 252, 252)
                                .addComponent(TChrome, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelaPrincipalLayout.setVerticalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalLayout.createSequentialGroup()
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                .addComponent(usuarioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NomeBanco)))))
                .addGap(32, 32, 32)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TChrome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Firefox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(TQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(iniciar)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClienteActionPerformed
      
//        
//        if (TLink.getText().contains("HP#")){
//            //http://HPtrairi:6141/#ativacao/login.jsp
//            new SystemOut().setVisible(true);
//            
//        }else{
//             new SystemOut().setVisible(false);
//        }
        
          if (boxCliente.getSelectedItem() == "CLARO CONTROLE" || boxCliente.getSelectedItem() == "CLARO CONTA") {          
           TClientenomeSubTipo.setVisible(true);
            addOferta.setVisible(true);
            addDenpendente.setVisible(true);
            iniciar.setVisible(true);
            gerarCpfAutomatico.setVisible(true);
            gerarCpfAutomatico.setSelected(true);
            TClientenomeVencimento.setVisible(true);
            TVencimentoFatura.setVisible(true);  
            boxClienteS.setVisible(true);
        } else{
              
            addOferta.setVisible(false);
            addDenpendente.setVisible(false);
            TVencimentoFatura.setVisible(false);
            TClientenomeVencimento.setVisible(false);
            boxClienteS.setVisible(true); 
          }         
        
        
        if (boxCliente.getFocusTraversalKeysEnabled() == true) {
            boxCliente.removeItem("SELECIONE");
        }

        if (boxCliente.getSelectedItem() != ("SELECIONE")) {

            TClientenomeSubTipo.setVisible(true);
            boxClienteS.setVisible(true);
            boxClienteS.removeAllItems();
            boxClienteS.addItem("SELECIONE");
            boxClienteS.addItem("3G");
            boxClienteS.addItem("GSM");
            TPlanoPreco.setVisible(true);
            planoPreco.setVisible(true);

        }
 
   if (boxCliente.getSelectedItem() == "CLARO CONTROLE" ){
       
         planoPreco.addItem("Claro Controle Mais 2GB + 100min");            
         planoPreco.addItem("Claro Controle Mais 3GB + 200min");            
         planoPreco.addItem("Claro Controle Mais 4GB + 500min");            
         planoPreco.addItem("Controle Mais 2,5GB + Min. Locais Ilimitados");
         planoPreco.addItem("Controle Mais 3,5GB + Min. Locais Ilimitados");
         planoPreco.addItem("Controle Mais 4GB + Min. Locais Ilimitados");
         planoPreco.addItem("Controle R$ 34,99 com dados");                 
         planoPreco.addItem("Controle R$ 49,99 com dados");
         planoPreco.addItem("Controle R$ 64,99 com dados");        
       
   }else{
       planoPreco.removeAllItems();
       TPlanoPreco.setVisible(false);
       planoPreco.setVisible(false);
     
   }


    }//GEN-LAST:event_boxClienteActionPerformed

    private void boxClienteSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClienteSActionPerformed

        
        boolean ativar =false;
        if(boxClienteS.isFocusOwner()== true){
        boxClienteS.removeItem("SELECIONE");
        ativar = true;
        }
               
           if (boxCliente.getSelectedItem() == "CLARO CONTROLE" || boxCliente.getSelectedItem() == "CLARO CONTA") {          
           TClientenomeSubTipo.setVisible(true);
            addOferta.setVisible(true);
            addDenpendente.setVisible(true);
            iniciar.setVisible(true);
            gerarCpfAutomatico.setVisible(true);
            gerarCpfAutomatico.setSelected(true);
            TClientenomeVencimento.setVisible(true);
            TVencimentoFatura.setVisible(true);
           
        }          
           
          if (boxCliente.getSelectedIndex() == 0 && boxClienteS.getSelectedIndex() == 0) {  
               if (ativar == true){   
           TClientenomeSubTipo.setVisible(true);
            addOferta.setVisible(false);
            addDenpendente.setVisible(false);
            iniciar.setVisible(true);
            gerarCpfAutomatico.setVisible(true);
            gerarCpfAutomatico.setSelected(true);
            TClientenomeVencimento.setVisible(false);
            TVencimentoFatura.setVisible(false);
              }
            
        }
                if (boxClienteS.getSelectedIndex() == 0)                   
                {    
                if (ativar == true){      
            TClientenomeSubTipo.setVisible(true);
       //     addOferta.setVisible(false);
         //   addDenpendente.setVisible(false);
      //      TClientenomeVencimento.setVisible(true);
      //      TVencimentoFatura.setVisible(true);  
            gerarCpfAutomatico.setVisible(true);
            gerarCpfAutomatico.setSelected(true);     
            iniciar.setVisible(true);
                }
                }


    }//GEN-LAST:event_boxClienteSActionPerformed

    private void gerarCpfAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarCpfAutomaticoActionPerformed

        if (gerarCpfAutomatico.isSelected() == true) {
            painelCpf.setVisible(false);
        } else {
            painelCpf.setVisible(true);
        }

    }//GEN-LAST:event_gerarCpfAutomaticoActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed


        Transfers.setDdd("11");
        
        
        
        try {
            //*******************************************************************************************
//                         Iniciando a validacao do campos                                  *
//*******************************************************************************************
//Verificando a link da pagina
            if (TLink.getText().equals("") || TLink.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Link WA Invalido", "Mensagem", JOptionPane.ERROR_MESSAGE);
                TLink.setBackground(new Color(255, 106, 106));
                return;
            } else {
                TLink.setBackground(oldColor);
            }
            //Verificando O Cliente
            if (boxCliente.getSelectedItem().equals("SELECIONE") || boxCliente.getSelectedItem().equals(null)) {
                JOptionPane.showMessageDialog(null, "Plano Invalido", "Mensagem", JOptionPane.ERROR_MESSAGE);
                boxCliente.setBackground(new Color(255, 106, 106));
                return;
            } else {
                boxCliente.setBackground(oldColor);
            }
            //Verificando o subTipo
            if (boxClienteS.getSelectedItem().equals("SELECIONE") || boxClienteS.getSelectedItem().equals(null)) {
                JOptionPane.showMessageDialog(null, "Tecnologia Invalida", "Mensagem", JOptionPane.ERROR_MESSAGE);
                boxClienteS.setBackground(new Color(255, 106, 106));
                return;
            } else {
                boxClienteS.setBackground(oldColor);
            }
            //Verificando o ciclo
            if (auxOferta == true) {
                //Verificando a oferta
                if (ofertaAtiva != 1 || boxCliente.getSelectedItem() != "IN.CONTROLE") {
                    JOptionPane.showMessageDialog(null, "Adicione uma Oferta ", "Mensagem", JOptionPane.ERROR_MESSAGE);
                    addOferta.setBackground(new Color(255, 106, 106));
                    return;
                } else {
                    addOferta.setBackground(oldColor);
                }
            }
            // Verificando a oferta
            if (boxCliente.getSelectedItem().equals("CLARO CONTA")){
                if ( ofertaAtiva == 0){
                    JOptionPane.showMessageDialog(null, "Adicione uma Oferta ", "Mensagem", JOptionPane.ERROR_MESSAGE);
                    addOferta.setBackground(new Color(255, 106, 106));
                    return;
                }else{
                     addOferta.setBackground(oldColor);
                }
                
            }

//*******************************************************************************************
//                       Fim a validacao do campos                                          *
//*******************************************************************************************
// pegando os dados do box e passando para classe       
            getSubTipo = boxClienteS.getSelectedItem().toString();
            getCliente = boxCliente.getSelectedItem().toString();

            TQuantidadeMassa = TQuantidade.getSelectedItem().toString();
            TVencimento = TVencimentoFatura.getText();

            if (TChrome.isSelected() == true) {
                tipoNavegador = "Chrome";
            }
            
              if (Firefox.isSelected() == true) {
                tipoNavegador = "Firefox";
            }
      
            
            if (iE.isSelected() == true) {
                tipoNavegador = "Ie";
            }

// pegando varios lista de CPF criando o parametro para oferta
            String texto2 = areaTextCpf.getText();
            StringTokenizer st2 = new StringTokenizer(texto2, "\n");
            while (st2.hasMoreTokens()) {
                String line2 = st2.nextToken();
                ListaCPF.add(line2);
                somaCPF++;
                System.out.println("Lista de CPF: " + ListaCPF);
            }

//Peagndo o link
            Tlink = TLink.getText();

            TipoNomeSubTipo = getSubTipo;
            T_Cliente = getCliente;
            auxCliente = boxCliente.getSelectedItem().toString();
            TplanoN = boxCliente.getSelectedIndex();
            System.out.println("Tipo de Cliente: " + getCliente);
            System.out.println("SubTipo da Empresa: " + TipoNomeSubTipo);

            if (habilitadoNavegador != "habilitado") {
                JOptionPane.showMessageDialog(null, "Selecione um Navegador");
                iE.setBackground(new Color(255, 106, 106));
                TChrome.setBackground(new Color(255, 106, 106));
                return;
            } else {
                TChrome.setBackground(oldColor);
                iE.setBackground(oldColor);
            }

            
            
            String texto4 = areaTextNumeroIccd.getText() ;
                StringTokenizer st4 = new StringTokenizer(texto4,"\n") ;
                while (st4.hasMoreTokens())
                {
                    String line4 = st4.nextToken();
                    iccd100.add(line4);            
                    System.out.println("Lista de Iccd: "+ iccd100);
                }
            
            
            
            
            
            
            
            
            
            liberarAutomacao = true;

            Automacao_WA auto = new Automacao_WA();
            auto.test();
  dispose();

// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(Tela_WA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_iniciarActionPerformed

    private void addOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOfertaActionPerformed

        ofertaAtiva = 1;
        SelecaoOferta oferta = new SelecaoOferta();
        oferta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_addOfertaActionPerformed

    private void iEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iEActionPerformed
        habilitadoNavegador = "habilitado";

        // TODO add your handling code here:
    }//GEN-LAST:event_iEActionPerformed

    private void TChromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TChromeActionPerformed

        habilitadoNavegador = "habilitado";

        // TODO add your handling code here:
    }//GEN-LAST:event_TChromeActionPerformed

    private void addDenpendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDenpendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDenpendenteActionPerformed

    private void TLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TLinkActionPerformed

    private void FirefoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirefoxActionPerformed
 habilitadoNavegador = "habilitado";        // TODO add your handling code here:
    }//GEN-LAST:event_FirefoxActionPerformed

    private void planoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planoPrecoActionPerformed
        
       









// TODO add your handling code here:
    }//GEN-LAST:event_planoPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_WA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_WA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_WA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_WA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Tela_WA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Firefox;
    public static javax.swing.JLabel NomeBanco;
    private javax.swing.JRadioButton TChrome;
    private javax.swing.JLabel TClienteNome;
    private javax.swing.JLabel TClientenomeSubTipo;
    private javax.swing.JLabel TClientenomeVencimento;
    private javax.swing.JTextField TLink;
    private javax.swing.JLabel TPlanoPreco;
    private javax.swing.JComboBox<String> TQuantidade;
    public static javax.swing.JTextField TVencimentoFatura;
    private componentes.UJPanelImagem TelaPrincipal;
    private javax.swing.JButton addDenpendente;
    private javax.swing.JButton addOferta;
    private javax.swing.JTextArea areaTextCpf;
    private javax.swing.JTextArea areaTextNumeroIccd;
    public static javax.swing.JComboBox<String> boxCliente;
    private javax.swing.JComboBox<String> boxClienteS;
    private javax.swing.JRadioButton gerarCpfAutomatico;
    private javax.swing.JRadioButton iE;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelCpf;
    public static javax.swing.JComboBox<String> planoPreco;
    private javax.swing.JScrollPane scrollCpf;
    private javax.swing.JScrollPane scrollNumeroContrato1;
    public static javax.swing.JLabel usuarioNome;
    // End of variables declaration//GEN-END:variables

}
