/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Impressao;

import MassaMobile.Tela_Mobile;
import Pacote_Principal.LoginBanco;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrique.rodrigues
 */
public class leitorPDF_Principal extends javax.swing.JFrame {

    private byte[] bytes = null;
    public static String Caminho = "", Caminho2 = "", Caminho3 = "",Caminho4 = "", CaminhoSaida = "";
    boolean btnArquivo = false;
    private Color oldColor = null;
    DefaultTableModel tabelaBd = null;
    ImpressaoPagina impressaoPagina = new ImpressaoPagina();

    /**
     * Creates new form leitorPDF
     */
    public leitorPDF_Principal() {
        initComponents();

        //-----------Preparando e incluido dados do Banco            
        tabelaBd = (DefaultTableModel) dadosValidacao.getModel();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        dadosValidacao.getColumnModel().getColumn(0).setCellRenderer(centralizado);
        dadosValidacao.getColumnModel().getColumn(1).setCellRenderer(centralizado);

        tabelaBd.setNumRows(0);

        //inserindo imagem no fundo 
        TelaPrincipal.setImagem(new File(LoginBanco.caminhoRedeLogin+"\\Imagem\\Tela_Principal2.jpg"));

        //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());

        //    this.setExtendedState(MAXIMIZED_BOTH);
        //---------Alterando o OptionPane  
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Segoe UI Semibold", Font.PLAIN, 15)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaPrincipal = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        Localizar = new javax.swing.JButton();
        btnMsisdn = new javax.swing.JRadioButton();
        btnBan = new javax.swing.JRadioButton();
        btArquivo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DadosLocalizar = new javax.swing.JTextArea();
        Panel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dadosValidacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Localizar Faturas");
        setResizable(false);

        TelaPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOCALIZAR FATURAS");

        Localizar.setBackground(new java.awt.Color(255, 153, 51));
        Localizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Localizar.setText("Localizar");
        Localizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalizarActionPerformed(evt);
            }
        });

        btnMsisdn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMsisdn.setForeground(new java.awt.Color(255, 255, 255));
        btnMsisdn.setText("Msisdn");
        btnMsisdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMsisdnActionPerformed(evt);
            }
        });

        btnBan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBan.setForeground(new java.awt.Color(255, 255, 255));
        btnBan.setText("  Ban ");
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        btArquivo.setBackground(new java.awt.Color(51, 204, 255));
        btArquivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btArquivo.setText("Arquivo");
        btArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArquivoActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inserir     Ban      ||      Msisdn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        DadosLocalizar.setColumns(20);
        DadosLocalizar.setRows(5);
        jScrollPane1.setViewportView(DadosLocalizar);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        dadosValidacao.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        dadosValidacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "              Dados", "                  Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dadosValidacao);
        if (dadosValidacao.getColumnModel().getColumnCount() > 0) {
            dadosValidacao.getColumnModel().getColumn(0).setMinWidth(140);
            dadosValidacao.getColumnModel().getColumn(0).setPreferredWidth(140);
            dadosValidacao.getColumnModel().getColumn(0).setMaxWidth(140);
            dadosValidacao.getColumnModel().getColumn(1).setMinWidth(178);
            dadosValidacao.getColumnModel().getColumn(1).setPreferredWidth(178);
            dadosValidacao.getColumnModel().getColumn(1).setMaxWidth(178);
        }

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
            .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TelaPrincipalLayout = new javax.swing.GroupLayout(TelaPrincipal);
        TelaPrincipal.setLayout(TelaPrincipalLayout);
        TelaPrincipalLayout.setHorizontalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TelaPrincipalLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(Localizar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(TelaPrincipalLayout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                    .addComponent(btnBan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMsisdn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)))
                    .addGroup(TelaPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        TelaPrincipalLayout.setVerticalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBan)
                    .addComponent(btnMsisdn))
                .addGap(18, 18, 18)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Localizar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalizarActionPerformed

        int soma = 0;
        ArrayList<String> Lista = new ArrayList<String>();
        String dados = "";

        // Verificando o tipo de entrada da lista
        if (btnBan.isSelected() == false && btnMsisdn.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Tipo de Busca Invalida", "Mensagem", JOptionPane.ERROR_MESSAGE);
            btnBan.setBackground(new Color(255, 106, 106));
            btnMsisdn.setBackground(new Color(255, 106, 106));
            return;
        } else {
            btnBan.setBackground(oldColor);
            btnMsisdn.setBackground(oldColor);
        }

        //Pegando dados do Customer
        String texto0 = DadosLocalizar.getText();
        StringTokenizer st0 = new StringTokenizer(texto0, "\n");

        while (st0.hasMoreTokens()) {
            String line0 = st0.nextToken();

            //Tratamento de ban ou msisdn    
            if (btnMsisdn.isSelected() == true) {
                String Aux = "";
                Aux = line0.substring(0, 2) + Aux + " " + line0.substring(2, 7) + Aux + " " + line0.substring(7, 11);
                line0 = Aux;
            }
            Lista.add(line0);
            soma++;
        }

        //Verificando campos
        if (DadosLocalizar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lista de Localizacao Invalida", "Mensagem", JOptionPane.ERROR_MESSAGE);
            DadosLocalizar.setBackground(new Color(255, 106, 106));
            return;
        } else {
            DadosLocalizar.setBackground(oldColor);
        }

        if (btnArquivo == false) {
            JOptionPane.showMessageDialog(null, "Caminho do Arquivo Invalido", "Mensagem", JOptionPane.ERROR_MESSAGE);
            btArquivo.setBackground(new Color(255, 106, 106));
            return;
        } else {
            btArquivo.setBackground(new Color(51, 204, 255));
        }

        //Criando a Pasta de Evidencia de Faturamento
        criarEvidencia();

        System.out.println("Lista Para Localizar: " + Lista);

        
        
        btArquivo.setEnabled(false);
        //validando os dados
        Panel1.setVisible(false);

        //   String file = ("C:\\Users\\henrique.rodrigues\\Desktop\\testePDF.pdf");
//            //para salvar
//            String caminho = null;
//            JFileChooser chooser = new JFileChooser();
//
//            int retorno = chooser.showSaveDialog(null);
//            
//            if (retorno==JFileChooser.APPROVE_OPTION){
//                caminho = chooser.getSelectedFile().getAbsolutePath()+".pdf"; 
//
//            }
        try {
            for (int i = 0; i <= Lista.size(); i++) {
                dados = Lista.get(i);
                 //verificando o segundo arquivo  
                  System.out.println("=======================");
                  System.out.println("Verificando 1º Arquivo");
                  System.out.println("=======================");
                if (impressaoPagina.ImpressaoPrincipal(Caminho, dados)) {
                    tabelaBd.addRow(new Object[]{dados, "Localizado"});
                } else {

                    if (Caminho2 == "") {
                        tabelaBd.addRow(new Object[]{dados, "Nao Encontrado"});
                    } else {

                        //verificando o segundo arquivo  
                        System.out.println("=======================");
                        System.out.println("Verificando 2º Arquivo");
                        System.out.println("=======================");
                        if (impressaoPagina.ImpressaoPrincipal(Caminho2, dados)) {
                            tabelaBd.addRow(new Object[]{dados, "Localizado"});
                        } else {

                            if (Caminho3 == "") {
                                tabelaBd.addRow(new Object[]{dados, "Nao Encontrado"});
                            } else {

                                //verificando o segundo arquivo  
                                 System.out.println("=======================");
                                 System.out.println("Verificando 3º Arquivo");
                                 System.out.println("=======================");
                                if (impressaoPagina.ImpressaoPrincipal(Caminho3, dados)) {
                                    tabelaBd.addRow(new Object[]{dados, "Localizado"});
                                } else {
                                    tabelaBd.addRow(new Object[]{dados, "Nao Encontrado"});
                                }
                            }
                             if (Caminho4 == "") {
                                tabelaBd.addRow(new Object[]{dados, "Nao Encontrado"});
                            } else {

                                //verificando o segundo arquivo  
                                 System.out.println("=======================");
                                 System.out.println("Verificando 4º Arquivo");
                                 System.out.println("=======================");
                                if (impressaoPagina.ImpressaoPrincipal(Caminho4, dados)) {
                                    tabelaBd.addRow(new Object[]{dados, "Localizado"});
                                } else {
                                    tabelaBd.addRow(new Object[]{dados, "Nao Encontrado"});
                                }
                            }
                        }

                    }

                }

            }

        } finally {
               // System.exit(0);
            //  JOptionPane.showMessageDialog(null, "Dados Localizados com sucesso");
            // dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_LocalizarActionPerformed

    private void btArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArquivoActionPerformed

        // Primeiro arquivo
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            Caminho = selectedFile.toString();
            System.out.println("Caminho do Arquivo:" + selectedFile);
            btnArquivo = true;
        }

        int retorno = JOptionPane.showConfirmDialog(null, "Deseja Inserir outro Arquivo PDF?",
                "Localizar Arquivo", JOptionPane.YES_NO_OPTION);
        if (retorno == 1) {
            return;
        } else {

            //Arquivo 2   
            returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                Caminho2 = selectedFile.toString();
                System.out.println("Caminho do Arquivo:" + selectedFile);
            }

        }
        int retorno2 = JOptionPane.showConfirmDialog(null, "Deseja Inserir outro Arquivo PDF?",
                "Localizar Arquivo", JOptionPane.YES_NO_OPTION);
        if (retorno2 == 1) {
            return;
        } else {

            //Arquivo 3   
            returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                Caminho3 = selectedFile.toString();
                System.out.println("Caminho do Arquivo:" + selectedFile);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btArquivoActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed

        if (btnBan.isSelected() == true) {
            btnMsisdn.setSelected(false);
        } else {
            btnMsisdn.setSelected(true);
            btnBan.setSelected(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanActionPerformed

    private void btnMsisdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMsisdnActionPerformed

        if (btnMsisdn.isSelected() == true) {
            btnBan.setSelected(false);
        } else {
            btnBan.setSelected(true);
            btnMsisdn.setSelected(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMsisdnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leitorPDF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leitorPDF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leitorPDF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leitorPDF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leitorPDF_Principal().setVisible(true);
            }
        });
    }

    //Classe de criacao da pasta de Evidencia
    public void criarEvidencia() {
        try {
            String NomeUsuario = System.getProperty("user.name");
            CaminhoSaida = "C:\\Documents and Settings\\" + NomeUsuario + "\\Desktop\\Evidencias de Faturamento";
            File diretorio = new File(CaminhoSaida);
            diretorio.mkdir();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao criar o diretorio Pasta de evidencia");
            System.out.println(ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DadosLocalizar;
    private javax.swing.JButton Localizar;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private componentes.UJPanelImagem TelaPrincipal;
    private javax.swing.JButton btArquivo;
    private javax.swing.JRadioButton btnBan;
    private javax.swing.JRadioButton btnMsisdn;
    private javax.swing.JTable dadosValidacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
