/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacote_Principal;

import Impressao.Impressao_Xml;
import MassaMobile.Automacao;
import static MassaMobile.Automacao.navegador;
import MassaMobile.Tela_Mobile;

import java.awt.Font;
import java.io.File;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author henrique.rodrigues
 */
public class Processando extends javax.swing.JFrame {

    /**
     * Creates new form Processando
     */
    public Processando() {
        initComponents();

        //inserindo imagem no fundo 
        TelaPrincipal.setImagem(new File(LoginBanco.caminhoRedeLogin+"\\Imagem\\Tela_Principal2.jpg"));
        //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());

        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/processo_1.gif")));    
       //  icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/"+Automacao.MsgErro+".gif")));                                                    
        //---------Alterando o OptionPane            
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Segoe UI Semibold", Font.PLAIN, 15)));

        
        log.setEditable(false);
        
        if (Automacao.Parar == true) {
            jButton1.setText("FINALIZADO");

            icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sucesso_1")));
            repaint();

        } else {
            jButton1.setText("PARAR");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        TelaPrincipal = new componentes.UJPanelImagem();
        icone = new javax.swing.JLabel();
        imgOrganizaa = new javax.swing.JLabel();
        imgClientee = new javax.swing.JLabel();
        imgContaa = new javax.swing.JLabel();
        imgAssinantee = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Em Execução");
        setResizable(false);

        icone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        imgOrganizaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgOrganizaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Uni.organiza.gif"))); // NOI18N

        imgClientee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgClientee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cliente.gif"))); // NOI18N

        imgContaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgContaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/conta.gif"))); // NOI18N

        imgAssinantee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgAssinantee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/assinante.gif"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("FINALIZADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        contador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        contador.setForeground(new java.awt.Color(255, 255, 255));
        contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contador.setText("0 / 0");

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        log.setColumns(20);
        log.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        log.setRows(5);
        log.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Eventos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 8))); // NOI18N
        jScrollPane1.setViewportView(log);

        javax.swing.GroupLayout TelaPrincipalLayout = new javax.swing.GroupLayout(TelaPrincipal);
        TelaPrincipal.setLayout(TelaPrincipalLayout);
        TelaPrincipalLayout.setHorizontalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(TelaPrincipalLayout.createSequentialGroup()
                            .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(imgClientee, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TelaPrincipalLayout.createSequentialGroup()
                                    .addComponent(imgContaa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(imgOrganizaa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(imgAssinantee, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        TelaPrincipalLayout.setVerticalGroup(
            TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgClientee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgContaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgOrganizaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgAssinantee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (Automacao.Parar == false && jButton1.getText().equals("PARAR")) {

            //   try {
            int retorno = JOptionPane.showConfirmDialog(null, "Deseja Parar a Execução?",
                    "Mensagem", JOptionPane.YES_NO_OPTION);
            System.out.println("retorno: " + retorno);
            if (retorno == 1) {
                return;

            } else {

                //System.out.println("Execução parada pelo Ususario");
                Tela_Mobile.liberarAutomacao = false;
                System.out.println("Execução parada pelo Ususario");
                //     Automacao.navegador.close();
                //     Automacao.navegador.quit();
                //retomando a tela principal
                  new Principal().setVisible(true);
                  
                try {

                } finally {
                    navegador.quit();
                    dispose();
                   
//                    System.exit(0);
                }
            }

        }

        if (jButton1.getText().equals("FINALIZADO")) {         
            try { 
                Tela_Mobile.liberarAutomacao = false;
                System.out.println("Execução Finalizado");
                if(Automacao.MsgErro == "N"){
                Impressao_Xml imp =  new Impressao_Xml();
                imp.Impressao();
                }
                new Principal().setVisible(true);
                 
            } finally {

               navegador.quit();
              
               
                   
                dispose();
              //  System.exit(0);
//              Automacao.navegador.close();
                //             Automacao.navegador.quit();
                //retomando a tela principal

            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.UJPanelImagem TelaPrincipal;
    public static javax.swing.JLabel contador;
    public static javax.swing.JLabel icone;
    public static javax.swing.JLabel imgAssinantee;
    public static javax.swing.JLabel imgClientee;
    public static javax.swing.JLabel imgContaa;
    public static javax.swing.JLabel imgOrganizaa;
    public static javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea log;
    // End of variables declaration//GEN-END:variables
}
