/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MassaMobile;

import Pacote_Principal.LoginBanco;
import Pacote_Principal.Transfers;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author henrique.rodrigues
 */
public class SelecaoOfertaAssinante extends javax.swing.JFrame {

       Transfers dados = new Transfers();
 
	public static String TipoOfertaTexto = "",TipoOfertaSelect, TxpathTituloAssinante , boxSelect;
	String ativarBuscaAssinante="",tituloAssinante;
        String titulo, plano;
    
    
    
    /**
     * Creates new form SelecaoOferta2
     */
    public SelecaoOfertaAssinante() {
        initComponents();
        
        
         //inserindo imagem no fundo 
        TelaOferta.setImagem(new File(LoginBanco.caminhoRedeLogin+"\\Imagem\\Tela_Principal2.jpg"));
        
             //Alterando o icone 
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagens/spread.png")).getImage());
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TelaOferta = new componentes.UJPanelImagem();
        jLabel1 = new javax.swing.JLabel();
        TClienteNome = new javax.swing.JLabel();
        nomeOferta = new javax.swing.JTextField();
        procurar = new javax.swing.JButton();
        ofertaDefault1 = new javax.swing.JRadioButton();
        ofertaDefault2 = new javax.swing.JRadioButton();
        ofertaDefault3 = new javax.swing.JRadioButton();
        ofertaDefault4 = new javax.swing.JRadioButton();
        TClienteNome1 = new javax.swing.JLabel();
        procurar1 = new javax.swing.JButton();
        ofertaDefault5 = new javax.swing.JRadioButton();
        ofertaDefault6 = new javax.swing.JRadioButton();
        ofertaDefault8 = new javax.swing.JRadioButton();
        ofertaDefault7 = new javax.swing.JRadioButton();
        Oferta_permanencia = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oferta Nivel Contrato");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OFERTAS NIVEL ASSINANTE");

        TClienteNome.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome.setForeground(new java.awt.Color(255, 255, 255));
        TClienteNome.setText("Oferta:");

        nomeOferta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N

        procurar.setBackground(new java.awt.Color(255, 153, 51));
        procurar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        procurar.setText("IR  para Pagina");
        procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurarActionPerformed(evt);
            }
        });

        ofertaDefault1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault1.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault1.setText("Passaporte Europa Voz/SMS/Dados                                                           R$19,99");
        ofertaDefault1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault1ActionPerformed(evt);
            }
        });

        ofertaDefault2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault2.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault2.setText("Passaporte Europa Voz/SMS/Dados - Embutido                                         R$ 0,00");
        ofertaDefault2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault2ActionPerformed(evt);
            }
        });

        ofertaDefault3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault3.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault3.setText("Passaporte Mundo Voz/SMS/Dados - Embutido                                           R$  0,00");
        ofertaDefault3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault3ActionPerformed(evt);
            }
        });

        ofertaDefault4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault4.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault4.setText("Passaporte Mundo Voz/SMS/Dados                                                               R$ 29,99");
        ofertaDefault4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault4ActionPerformed(evt);
            }
        });

        TClienteNome1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TClienteNome1.setForeground(new java.awt.Color(255, 255, 255));
        TClienteNome1.setText("( Plano default )");

        procurar1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        procurar1.setText("OK");
        procurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procurar1ActionPerformed(evt);
            }
        });

        ofertaDefault5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault5.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault5.setText("Passaporte Américas Voz/SMS/Dados                                                               R$9,99");
        ofertaDefault5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault5ActionPerformed(evt);
            }
        });

        ofertaDefault6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault6.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault6.setText("Passaporte Américas Voz/SMS/Dados - Embutido                                        R$ 0,00");
        ofertaDefault6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault6ActionPerformed(evt);
            }
        });

        ofertaDefault8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault8.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault8.setText(" Claro Controle Mais     Claro Controle Mais 4GB + Ilimitado                           R$  00,0");
        ofertaDefault8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault8ActionPerformed(evt);
            }
        });

        ofertaDefault7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        ofertaDefault7.setForeground(new java.awt.Color(255, 255, 255));
        ofertaDefault7.setText("Claro Controle Mais     Claro Controle Mais 2GB + 100min                             R$  00,0");
        ofertaDefault7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofertaDefault7ActionPerformed(evt);
            }
        });

        Oferta_permanencia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        Oferta_permanencia.setForeground(new java.awt.Color(255, 255, 255));
        Oferta_permanencia.setText("Permanencia Multa PF       ");
        Oferta_permanencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Oferta_permanenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaOfertaLayout = new javax.swing.GroupLayout(TelaOferta);
        TelaOferta.setLayout(TelaOfertaLayout);
        TelaOfertaLayout.setHorizontalGroup(
            TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaOfertaLayout.createSequentialGroup()
                .addGroup(TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaOfertaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(TelaOfertaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(TClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeOferta))))
                    .addGroup(TelaOfertaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ofertaDefault1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault3, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault4, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault6, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault7, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ofertaDefault8, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Oferta_permanencia, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelaOfertaLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(TClienteNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaOfertaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaOfertaLayout.createSequentialGroup()
                        .addComponent(procurar1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaOfertaLayout.createSequentialGroup()
                        .addComponent(procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        TelaOfertaLayout.setVerticalGroup(
            TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(procurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelaOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TClienteNome)
                    .addComponent(nomeOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(ofertaDefault1)
                .addGap(8, 8, 8)
                .addComponent(ofertaDefault2)
                .addGap(8, 8, 8)
                .addComponent(ofertaDefault4)
                .addGap(8, 8, 8)
                .addComponent(ofertaDefault3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ofertaDefault5)
                .addGap(8, 8, 8)
                .addComponent(ofertaDefault6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ofertaDefault7)
                .addGap(7, 7, 7)
                .addComponent(ofertaDefault8)
                .addGap(9, 9, 9)
                .addComponent(Oferta_permanencia)
                .addGap(26, 26, 26)
                .addComponent(TClienteNome1)
                .addGap(18, 18, 18)
                .addComponent(procurar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ofertaDefault2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault2ActionPerformed
        ofertaDefault1.setSelected(false);
        ofertaDefault8.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
				if(ofertaDefault2.isSelected()==true) {
				nomeOferta.setText("");
				tituloAssinante = "EUROPA_EMBUTIDO";	         
			}else {
				tituloAssinante  = "";
			}



        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault2ActionPerformed

    private void ofertaDefault3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault3ActionPerformed
        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault8.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
				
				if(ofertaDefault4.isSelected()==true) {
				nomeOferta.setText("");
				tituloAssinante = "MUNDO_EMBUTIDO";
	                        }else {
				tituloAssinante = "";
			}



        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault3ActionPerformed

    private void ofertaDefault4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault4ActionPerformed
        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault8.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
				
				if(ofertaDefault3.isSelected()==true) {
				nomeOferta.setText("");
				tituloAssinante = "MUNDO";	         
			}else {
				tituloAssinante  = "";
			}




        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault4ActionPerformed

    private void procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurarActionPerformed

       if( Tela_Mobile.boxClienteAssinante.getSelectedItem() == "SELECIONE"){
            JOptionPane.showMessageDialog(null, "Primeiro Selecione o Tipo de Assinante!");
            return;
       }

		ativarBuscaAssinante = "N";
	try {
		
            if (Tela_Mobile.boxClienteAssinante.getSelectedItem() == "Pós-Pago Tecnologia GSM" ){
		Runtime.getRuntime().exec("cmd.exe /c start chrome.exe \"\\\\srv-arq-02.intra_sp_spread\\\\Fabrica_de_Testes\\\\Fábrica de Teste Spread\\\\Automacao_mobile\\\\Ofertas_offline\\\\GSM -Assinante - Ofertas Adicionais.html");
            }
            
            if (Tela_Mobile.boxClienteAssinante.getSelectedItem() == "Pós-Pago Tecnologia 3G" ){
		Runtime.getRuntime().exec("cmd.exe /c start chrome.exe \"\\\\srv-arq-02.intra_sp_spread\\\\Fabrica_de_Testes\\\\Fábrica de Teste Spread\\\\Automacao_mobile\\\\Ofertas_offline\\\\POS-CONTROLE -Assinante - Ofertas Adicionais.html");
            }   
            if (Tela_Mobile.boxClienteAssinante.getSelectedItem() == "Controle Tecnologia 3G" ){
		Runtime.getRuntime().exec("cmd.exe /c start chrome.exe \"\\\\srv-arq-02.intra_sp_spread\\\\Fabrica_de_Testes\\\\Fábrica de Teste Spread\\\\Automacao_mobile\\\\Ofertas_offline\\\\CONTROLE_3G-Assinante - Ofertas Adicionais.html");
            }  
                
            if (Tela_Mobile.boxClienteAssinante.getSelectedItem() == "Pos-Pago Banda Larga" ){
		Runtime.getRuntime().exec("cmd.exe /c start chrome.exe \"\\\\srv-arq-02.intra_sp_spread\\\\Fabrica_de_Testes\\\\Fábrica de Teste Spread\\\\Automacao_mobile\\\\Ofertas_offline\\\\BANDA_LARGA - Assinante - Ofertas Adicionais.html");
            }  
                
                
	} catch (IOException e1) {					
			e1.printStackTrace();
	}

        // TODO add your handling code here:
    }//GEN-LAST:event_procurarActionPerformed

    private void ofertaDefault1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault1ActionPerformed
        ofertaDefault8.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
     			
				if(ofertaDefault1.isSelected()==true) {
				nomeOferta.setText("");
				ofertaDefault2.setSelected(false);
				tituloAssinante = "EUROPA";		
				}else {
					tituloAssinante = "";
		
				}




        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault1ActionPerformed

    private void procurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procurar1ActionPerformed


				String oF = nomeOferta.getText();
	
				if (nomeOferta.getText().equals("") && ofertaDefault1.isSelected() == false && ofertaDefault2.isSelected() == false && ofertaDefault3.isSelected() == false
						&& ofertaDefault4.isSelected() == false && ofertaDefault5.isSelected() == false && ofertaDefault6.isSelected() == false
                                                 && ofertaDefault7.isSelected() == false && ofertaDefault8.isSelected() == false && Oferta_permanencia.isSelected() == false) {
					JOptionPane.showMessageDialog(null, "Selecione 1 tipo de oferta Nivel Assinante");return;}
				
				
				if (nomeOferta.getText() != ""){
                                    
				dados.setNomeOfertaAssinante(nomeOferta.getText());
                                
                                }
                                 dados.setAtivarBuscaAssinante("N");
				
				if (ofertaDefault1.isSelected() == true ) {
					System.out.print("Oferta 1  Ativa \n");
					TipoOfertaSelect = ativarBuscaAssinante;
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
                                        dados.setNomeOfertaAssinante(ofertaDefault1.getText());
				}
				if (ofertaDefault2.isSelected() == true) {
					System.out.print("Oferta 2  Ativa \n");
					TipoOfertaSelect = ativarBuscaAssinante;
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
                                        dados.setNomeOfertaAssinante(ofertaDefault2.getText());
				}
			
				if (ofertaDefault3.isSelected() == true) {
					System.out.print("Oferta 3  Ativa \n");
					TipoOfertaSelect = ativarBuscaAssinante;
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
                                        dados.setNomeOfertaAssinante(ofertaDefault3.getText());
				}
				if (ofertaDefault4.isSelected() == true) {
					System.out.print("Oferta 4  Ativa \n");
					TipoOfertaSelect = ativarBuscaAssinante;
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
                                        dados.setNomeOfertaAssinante(ofertaDefault4.getText());
				}
                                if (ofertaDefault5.isSelected() == true) {
					System.out.print("Oferta 5  Ativa \n");
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
                                        dados.setNomeOfertaAssinante(ofertaDefault5.getText());
				}
				
                                if (ofertaDefault6.isSelected() == true) {
					System.out.print("Oferta 6  Ativa \n");
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
					dados.setNomeOfertaAssinante(ofertaDefault6.getText());
				}
                                 if (ofertaDefault7.isSelected() == true) {
					System.out.print("Oferta 7  Ativa \n");
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
					dados.setNomeOfertaAssinante(ofertaDefault7.getText());
				}
                                if (ofertaDefault8.isSelected() == true) {
					System.out.print("Oferta 8  Ativa \n");
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
					dados.setNomeOfertaAssinante(ofertaDefault8.getText());
				}
                                
                                        if (Oferta_permanencia.isSelected() == true) {
					System.out.print("Oferta 9  Ativa \n");
					TxpathTituloAssinante = tituloAssinante;
                                        dados.setAtivarBuscaAssinante("S");
					dados.setNomeOfertaAssinante(Oferta_permanencia.getText());
				}
				
				
			     dados.setAtivaOfertaAssinante(true);
		             dispose();




        // TODO add your handling code here:
    }//GEN-LAST:event_procurar1ActionPerformed

    private void ofertaDefault5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault5ActionPerformed
        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault8.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
				if(ofertaDefault5.isSelected()==true) {
				nomeOferta.setText("");
				tituloAssinante = "EUROPA";
	                        }else {
				tituloAssinante = "";
			}

        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault5ActionPerformed

    private void ofertaDefault6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault6ActionPerformed
        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault8.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";
				
				if(ofertaDefault6.isSelected()==true) {
				nomeOferta.setText("");
				tituloAssinante = "EUROPA_MUNDO";
	                        }else {
				tituloAssinante = "";
			}        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault6ActionPerformed

    private void ofertaDefault8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault8ActionPerformed

        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";

        if(ofertaDefault8.isSelected()==true) {
            nomeOferta.setText("");
            titulo = "";
            plano  = "//*[@id=\"groupId_414302387_3\"]/td[1]/input";
            ativarBuscaAssinante ="8";
            boxSelect = "oferta 8";
            tituloAssinante = "Claro Controle Mais 4GB + Ilimitado";
        }else {
            titulo = "";
            plano = "";
            ativarBuscaAssinante ="";
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault8ActionPerformed

    private void ofertaDefault7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofertaDefault7ActionPerformed

        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);       
        ofertaDefault8.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";

        if(ofertaDefault7.isSelected()==true) {
            nomeOferta.setText("");
            titulo = " ";
            plano  = "//*[@id=\"groupId_414302387_0\"]/td[1]/input";
            ativarBuscaAssinante ="7";
            boxSelect = "oferta 7";
           tituloAssinante = "Claro Controle Mais 2GB + 100min";
        }else {
            titulo = "";
            plano = "";
            ativarBuscaAssinante ="";
           
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ofertaDefault7ActionPerformed

    private void Oferta_permanenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Oferta_permanenciaActionPerformed


        ofertaDefault1.setSelected(false);
        ofertaDefault2.setSelected(false);
        ofertaDefault3.setSelected(false);
        ofertaDefault4.setSelected(false);
        ofertaDefault5.setSelected(false);
        ofertaDefault6.setSelected(false);       
        ofertaDefault8.setSelected(false);
        ofertaDefault7.setSelected(false);
        titulo = "";
        plano = "";
        ativarBuscaAssinante ="";
        tituloAssinante= "";

        if(Oferta_permanencia.isSelected()==true) {
            nomeOferta.setText("");
            titulo = "//*[@id=\"groupHeader_380455420\"]/td[1]/img";
            plano  = "//*[@id=\"groupId_380455420_16\"]/td[1]/input";                
            ativarBuscaAssinante ="9";
            boxSelect = "oferta 9";
           tituloAssinante = "Permanencia Multa PF";
        }else {
            titulo = "";
            plano = "";
            ativarBuscaAssinante ="";
           
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_Oferta_permanenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoOfertaAssinante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoOfertaAssinante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoOfertaAssinante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoOfertaAssinante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoOfertaAssinante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JRadioButton Oferta_permanencia;
    private javax.swing.JLabel TClienteNome;
    private javax.swing.JLabel TClienteNome1;
    private componentes.UJPanelImagem TelaOferta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeOferta;
    private javax.swing.JRadioButton ofertaDefault1;
    private javax.swing.JRadioButton ofertaDefault2;
    private javax.swing.JRadioButton ofertaDefault3;
    private javax.swing.JRadioButton ofertaDefault4;
    private javax.swing.JRadioButton ofertaDefault5;
    private javax.swing.JRadioButton ofertaDefault6;
    private javax.swing.JRadioButton ofertaDefault7;
    private javax.swing.JRadioButton ofertaDefault8;
    private javax.swing.JButton procurar;
    private javax.swing.JButton procurar1;
    // End of variables declaration//GEN-END:variables
}
